services:
  - type: web
    name: rolfing-web
    runtime: java11
    plan: free
    buildCommand: ./gradlew clean build
    startCommand: java -cp build/libs/rolfing.war com.rolfing.server.JettyServer
    envVars:
      - key: PORT
        value: 8080
